url: https://Agilewarriors.github.io
baseurl: /

# Site settings
title: Agile Warriors
email: agileworrios1@gmail.com  
description: "The Glappy Agile Warriors Portfolio Website"


# Team names, titles and social links
people:
- name: Faustin DEMESSE
  pic: Faustin
  position: Product Owner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/faustin-demesse-bb21a7155/
    - title: google-plus
      url: zafrinss1@gmail.com

- name: Dorothy F
  pic: Dorothy
  position: Scrum Master
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/dorothy-simo/
    - title: yahoo
      url: dorothy.simo@yahoo.se 

- name: Kotartee Torh
  pic: Kotartee
  position: Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kotartee-torh/
    - title: google-plus
      url: kotarteetorh46@gmail.com

- name: Esther Osazuwa 
  pic: Esther
  position: Tester
  social:
    - title: google-plus
      url: Osazuwaesther87@gmail.com

- name: Lilly 
  pic: Lilly
  position: Product Owner
  social:
    - title: google-plus
      url: #

- name: Venus Tadonke
  pic: Venus
  position: Developer
  social:
    - title: google-plus
      url: tadonkevenus@gmail.com
      
- name: Justice
  pic: Justice
  position: Product Manager
  social:
    - title: google-plus
      url: #

- name: Charles Akpoghenobor
  pic: Charles
  position: Data Analyst
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Beckly T
  pic: Beckly
  position: Developer
  social:
    - title: yahoo
      url: tabetahpaul@yahoo.com

- name: JPurple
  pic: jpurple
  position: Lead Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ngnepedoh-irving-craig/
    - title: google-plus
      url: nirvingcraig99@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: #
  - title: github
    url: http://github.com/Agilewarriors

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
