url: https://Agilewarriors.github.io
baseurl: /

# Site settings
title: Agile Warriors
email: agileworrios1@gmail.com  
description: "The Glappy Agile Warriors Portfolio Website"


# Team names, titles and social links
people:
 - name: Faustin DEMESSE
  pic: Faustin
  position: Product Owner
  social:
   - title: linkedin
    url: #
   - title: twitter
    url: #
   - title: facebook
    url: #
   - title: stack-overflow
    url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
